language: python
python:
  - "2.6"
  - "2.7"
install: 
  - "pip install -r hamster/requirements.pip --use-mirrors"
  - "pip install coveralls coverage --use-mirrors"
script:
  - cd hamster && coverage run --source=jobs manage.py test
#after_success:
#  - coveralls
